import "@/styles/globals.css";

import AppProvider from "@/components/providers/reduxProviders";

export const metadata = {
  title: "Features",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <AppProvider>{children}</AppProvider>
    </>
  );
}
