import { Poppins } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/Header";
import Providers from "@/components/providers/providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={poppins.className}>
        <Providers>
          <Header />
          <div className="max-w-5xl m-auto w-full p-4">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
